### ISSUE TITLE
Snap does not run on Ubuntu 20.04

### ISSUE THREAD

**Issue by SuperCuber** [JayJay1989/Pretzel-Desktop#1]
Running `pretzeldesktop` fails with
```
/snap/pretzeldesktop/2/pretzeldesktop: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```
Installing `libgconf-2-4` has no effect even after reinstalling the snap.

**Comment by JayJay1989** [comment]
Thanks for reporting. Will look into this. 
I have the same issue when installing from the snap store.

**Comment by JayJay1989** [comment]
I think i got it fixed. Its Currently being processed by snapcraft.io

**Comment by JayJay1989** [comment]
Aaand they switched to the alpha player. The old one will not work. Will need some days to port it to linux

**Comment by JayJay1989** [comment]
ok, tried initial porting `sudo snap install pretzeldesktop --channel=beta`

**Comment by JayJay1989** [comment]
Ported the new Pretzel app, it still in beta on snapcraft.
Install it with `sudo snap install pretzeldesktop --channel=beta`
