### ISSUE TITLE
Pretzel App from Snapstore stuck in reload loop

### ISSUE THREAD

**Issue by deadpoetix** [JayJay1989/Pretzel-Desktop#13]
Just started seeing this on Xubuntu 22.04 - had been working prior. Reinstalling from Snap nor compiling through npm. Client will walk through Twitch login successfully, flash the dashboard for a half-second, and the give the error "Submit Report" or "Just reload the app." Using the web version of the player through Chrome works as expected. 

Also made sure all configuration files were removed prior to reinstall - only error messages in the console are the following: 

Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" subproperty "pretzel" setting: xdg-settings: default-url-scheme-handler not implemented for xfce
Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" subproperty "pretzel-desktop" setting: xdg-settings: default-url-scheme-handler not implemented for xfce
MainWindow Loading:  https://play.pretzel.rocks
Instantiating PickFileChannel
Setting up IPCRequest.ts Channel:  write_track_info
Setting up IPCRequest.ts Channel:  pick_file
Setting up IPCRequest.ts Channel:  [ 'register_global_shortcut', 'remove_global_shortcut' ]
Setting up IPCRequest.ts Channel:  clear_account_data
(node:46593) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `pretzeldesktop --trace-deprecation ...` to show where the warning was created)

The two messages regarding the url-scheme-handler are messages displayed in the UI which I had prior, and didn't affect functionality. I attempted using the 'pretzeldesktop --trace-deprecation' to see if it would give more info, but seemed to return the same.

**Comment by JayJay1989** [comment]
fixed in latest release
