### ISSUE TITLE
[request] Arch Linux AUR support

### ISSUE THREAD

**Issue by lorddickfist** [JayJay1989/Pretzel-Desktop#4]
Instead of only supporting appimage/snap You can widen support and availability range if you add it to the AUR.

**Comment by JayJay1989** [comment]
Will do some research on how to do it this weekend. 
If you have a working build for it, you can do a pull-request

**Comment by JayJay1989** [comment]
see [Releases](https://github.com/JayJay1989/Pretzel-Desktop/releases/tag/v2.10.0)
