### ISSUE TITLE
Pop OS not loading App on snap installer

### ISSUE THREAD

**Issue by ChisdealHDYT** [JayJay1989/Pretzel-Desktop#5]
![image](https://user-images.githubusercontent.com/18028479/128332021-a5dba599-8a1e-47b3-ada4-631a89a9d148.png)

blanks Screen with unable open console check errors.

Its Linux OS as Pop OS

**Comment by JayJay1989** [comment]
can you launch the app through the console and give me the console log for it?

**Comment by ChisdealHDYT** [comment]
whats command for it?

**Comment by JayJay1989** [comment]
`pretzel-desktop`

**Comment by ChisdealHDYT** [comment]
when we run `pretzeldesktop` it opens up fully but as pretzel.desktop file. errors there so i can confirm is working by console but .desktop file doesnt.

**Comment by JayJay1989** [comment]
ok, let me fix that. Thanks for reporting

**Comment by JayJay1989** [comment]
Hmm, did it create a desktop icon by itself or did you create one?

**Comment by ChisdealHDYT** [comment]
it created it, it spit some errors out for something do with `/home/user/.env` and it still loaded on Termital, but as Desktop self. it gives it blank page. i cant confirm much because i not using Pop OS. 1 of my friend since him moved from windows to Pop Os but this was taken on discord call then i had to leave call because i got some stuff todo today.

i recommended if can, run VM OS of Pop OS and try it. 

i normally i use ubuntu but never used pop OS

**Comment by JayJay1989** [comment]
Well, i'm in a vm right now. After installing the snap, not a single icon is created. Sound more like a pop os problem.

**Comment by ChisdealHDYT** [comment]
ah ok, hope get fixed, i know Terminal works fine just Desktop side not.

**Comment by JayJay1989** [comment]
try appimage instead. See [releases](https://github.com/JayJay1989/Pretzel-Desktop/releases/tag/v2.10.0)
