### ISSUE TITLE
trouble compiling using given instructions

### ISSUE THREAD

**Issue by mtsl8** [JayJay1989/Pretzel-Desktop#6]
Artix(Arch) Linux user - interested in working on packaging for AUR #4. Not well versed in npm but it seems perhaps I'm missing a dependency or something has changed since you wrote the instructions.. 

Building off the latest stable release Pretzel-Desktop-2.1.2.tar.gz source package;

the "npm install" step seems to work, although it mentions what seem like important security updates available for axios and electron:

> axios  <=0.21.1 
> Severity: high
> Incorrect Comparison in axios - https://github.com/advisories/GHSA-cph5-m8f7-6c5x
> Server-Side Request Forgery in Axios - https://github.com/advisories/GHSA-4w2v-q235-vp99

> electron  <11.5.0
> Severity: moderate
> Sandboxed renderers can obtain thumbnails of arbitrary files through the nativeImage API - https://github.com/advisories/GHSA-mpjm-v997-c4h4

the "npm compile" step does not work, as npm does not recognize the command.

am I missing something?

going ahead with the build, requires "npm run build" which differs from your instructions.
(not expecting it to work since the typescript is not compiled..) yields error:

>Application entry file "src/build/desktop/src/index.js" in the ".../Pretzel-Desktop-2.1.2/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.

any help would be appreciated.

**Comment by JayJay1989** [comment]
the command is `npm run compile`.

**Comment by JayJay1989** [comment]
Both issues are resolved.
Electron updated to: 12.1.2
Axios updated to: 0.25.0

Likely i forgot to update the `package.json` last time to include the compile step.

**Comment by mtsl8** [comment]
Thanks, this got it much farther along. One small issue with the new instructions is that "npm install" does not require the "run". the rest work correctly. The bigger issue is that I didn't realize this program hard dependeds on snapcraft, therefore has a hardcoded systemd dependency which makes it unusable for me. To reiterate I am using Artix, a fork of Arch. Was interested in making a PKGBUILD for the AUR but if there is no way to build without snapcraft then I will just use pretzel from the web. thanks.

**Comment by mtsl8** [comment]
Apparently it is only a build dependency, because I was able to install and run your Arch package fine without snapcraft or systemd installed. FYI standard Arch package extensions are of the form "package.pkg.tar.zst" so it worked perfectly fine after renaming. Thanks for creating this!
